-- Data Types

-- CREATE TABLE

CREATE TABLE IF NOT EXISTS account(
	user_id SERIAL PRIMARY KEY,
	user_name VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	created_on TIMESTAMP NOT NULL,
	last_login TIMESTAMP
);

CREATE TABLE roles(
	role_id SERIAL PRIMARY KEY,
	role_name VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS roles;

CREATE TABLE account_roles(
	user_id INT NOT NULL,
	role_id INT NOT NULL,
	grant_date TIMESTAMP,
	PRIMARY KEY (user_id, role_id),
	FOREIGN KEY(role_id)
		REFERENCES roles (role_id),
	FOREIGN KEY (user_id)
		REFERENCES account (user_id)
);

-- SELECT INTO
SELECT title,film_id, rental_duration
INTO TABLE film_r
FROM film
WHERE rating = 'R' AND rental_duration = 5
ORDER BY title;

SELECT * FROM film_r;

SELECT film_id, title, length
INTO TEMP TABLE short_film
FROM film
WHERE length < 60;

SELECT * FROM short_film;

-- CREATE TABLE AS

CREATE TABLE action_film AS
SELECT film_id,
		title,
		release_year,
		length,
		rating
FROM film INNER JOIN film_category USING(film_id)
WHERE category_id = 1;

SELECT * FROM action_film;

CREATE TABLE IF NOT EXISTS film_rating(rating_film, film_count)
AS SELECT rating, COUNT(film_id)
FROM film
GROUP BY rating;

SELECT * FROM film_rating;

-- SERIAL

CREATE TABLE fruits(
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL
);

INSERT INTO fruits(name)
VALUES('Orange');

INSERT INTO fruits(id, name)
VALUES(DEFAULT, 'APPLE');

SELECT * FROM fruits;

SELECT currval(pg_get_serial_sequence('fruits', 'id'));

INSERT INTO fruits(name)
VALUES('Grapes')
RETURNING id;

-- Sequences

CREATE SEQUENCE mysequence
INCREMENT 5
START 100;

SELECT nextval('mysequence');

CREATE SEQUENCE IF NOT EXISTS three
INCREMENT -1
MINVALUE 1
MAXVALUE 3
START 3
CYCLE;

SELECT nextval('three');

CREATE SEQUENCE IF NOT EXISTS nocycle
INCREMENT -1
MINVALUE 1
MAXVALUE 3
START 3;

SELECT nextval('nocycle');

DROP TABLE IF EXISTS order_details;
CREATE TABLE order_details(
	order_id SERIAL,
	item_id INT NOT NULL,
	item_text VARCHAR NOT NULL,
	price DEC(10, 2) NOT NULL,
	PRIMARY KEY(order_id, item_id)
);

CREATE SEQUENCE order_item_id
START 10
INCREMENT 10
MINVALUE 10
OWNED BY order_details.item_id;

INSERT INTO order_details(order_id, item_id, item_text, price)
VALUES (100, nextval('order_item_id'),'DVD Player',100),
    (100, nextval('order_item_id'),'Android TV',550),
    (100, nextval('order_item_id'),'Speaker',250);
	
SELECT * FROM order_details;

SELECT relname sequence_name
FROM pg_class
WHERE relkind = 'S';

DROP TABLE order_details;

-- Identity Column

DROP TABLE IF EXISTS color;
CREATE TABLE color(
	color_id INT GENERATED ALWAYS AS IDENTITY,
	color_name VARCHAR NOT NULL
);

INSERT INTO color(color_name)
VALUES('Red');

SELECT * FROM color;

INSERT INTO color(color_id, color_name)
OVERRIDING SYSTEM VALUE
VALUES(3, 'Green');

DROP TABLE IF EXISTS color;
CREATE TABLE color(
	color_id INT GENERATED BY DEFAULT AS IDENTITY,
	color_name VARCHAR NOT NULL
);

INSERT INTO color(color_name)
VALUES('White');


SELECT * FROM color;

INSERT INTO color(color_id, color_name)
VALUES (2, 'Red');

DROP TABLE IF EXISTS color;
CREATE TABLE color(
	color_id INT GENERATED BY DEFAULT AS IDENTITY
	(START WITH 100 INCREMENT BY 10),
	color_name VARCHAR NOT NULL
);

INSERT INTO color(color_name)
VALUES ('Orange');

SELECT * FROM color;

INSERT INTO color(color_name)
VALUES ('Purple');

CREATE TABLE shape(
	shape_id INT NOT NULL,
	shape_name VARCHAR NOT NULL
);

ALTER TABLE shape
ALTER COLUMN shape_id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE shape
ALTER COLUMN shape_id SET GENERATED BY DEFAULT;

ALTER TABLE shape
ALTER COLUMN shape_id
DROP IDENTITY IF EXISTS;

-- ALTER TABLE

DROP TABLE IF EXISTS links;
CREATE TABLE links(
	link_id SERIAL PRIMARY KEY,
	title VARCHAR(512) NOT NULL,
	url VARCHAR(1024) NOT NULL	
);

ALTER TABLE links
ADD COLUMN active boolean;  

ALTER TABLE links
DROP COLUMN active;

ALTER TABLE links
RENAME COLUMN title TO link_title;

ALTER TABLE links
ADD COLUMN target VARCHAR(10);

ALTER TABLE links
ALTER COLUMN target
SET DEFAULT '_blank';

INSERT INTO links(link_title, url)
VALUES ('PostgreSQL Tutorial','https://www.postgresqltutorial.com/');

SELECT * FROM links;

ALTER TABLE links
ADD CHECK (target IN('_self', '_blank', '_parent', '_top'));

INSERT INTO links(link_title,url,target)
VALUES ('PostgreSQL','http://www.postgresql.org/','whatever');

ALTER TABLE links
ADD CONSTRAINT unique_url UNIQUE ( url );

INSERT INTO links(link_title, url)
VALUES ('PostgreSQL','https://www.postgresqltutorial.com/');

ALTER TABLE links
RENAME TO urls;

--Rename Table: A Step-by-Step Guide

DROP TABLE IF EXISTS vendors;
CREATE TABLE vendors(
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL
);

ALTER TABLE vendors RENAME TO suppliers;

CREATE TABLE supplier_groups(
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL
);

ALTER TABLE suppliers
ADD COLUMN group_id INT NOT NULL;

ALTER TABLE suppliers
ADD FOREIGN KEY (group_id) REFERENCES supplier_groups(id);

CREATE VIEW supplier_date
AS SELECT
	s.id,
	s.name,
	g.name supply_group
FROM suppliers s 
INNER JOIN supplier_groups g ON g.id = s.group_id;

ALTER TABLE supplier_groups RENAME TO groups;

--ADD COLUMN: Add One Or More Columns To a Table

DROP TABLE IF EXISTS customers1 CASCADE;
CREATE TABLE customers1(
	id SERIAL PRIMARY KEY,
	customer_name VARCHAR NOT NULL
);

ALTER TABLE customers1
ADD COLUMN phone VARCHAR;

ALTER TABLE customers1
ADD COLUMN fax VARCHAR,
ADD COLUMN email VARCHAR;

INSERT INTO customers1(customer_name)
VALUES ('Apple'),
		('Samsung'),
		('Sony');
		
SELECT * FROM customers1;

ALTER TABLE customers1
ADD COLUMN contact_name VARCHAR NOT NULL;

ALTER TABLE customers1
ADD COLUMN contact_name VARCHAR;

UPDATE customers1
SET contact_name = 'John'
WHERE id = 1;

UPDATE customers1
SET contact_name = 'Mary'
WHERE id = 2;

UPDATE customers1
SET contact_name = 'Lily'
WHERE id = 3;

ALTER TABLE customers1
ALTER COLUMN contact_name SET NOT NULL;

--DROP COLUMN: Remove One or More Columns of a Table
CREATE TABLE publishers(
	publisher_id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL
);

CREATE TABLE categories1(
	category_id SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL
);

CREATE TABLE books(
	book_id SERIAL PRIMARY KEY,
	title VARCHAR NOT NULL,
	isbn VARCHAR NOT NULL,
	published_date DATE NOT NULL,
	description VARCHAR,
	category_id INT NOT NULL,
	publisher_id INT NOT NULL,
	FOREIGN KEY (publisher_id) REFERENCES publishers(publisher_id),
	FOREIGN KEY (category_id) REFERENCES categories(category_id)

);

CREATE VIEW book_info
AS SELECT book_id,
	title,
	isbn,
	published_date,
	name
FROM books b INNER JOIN publishers USING (publisher_id)
ORDER BY title;

ALTER TABLE books
DROP COLUMN category_id;

ALTER TABLE books
DROP COLUMN publisher_id;

ALTER TABLE books
DROP COLUMN publisher_id CASCADE;

ALTER TABLE books
DROP COLUMN isbn,
DROP COLUMN description;

--Change Column Type: Step-by-Step Examples
CREATE TABLE assets(
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	asset_no VARCHAR NOT NULL,
	description TEXT,
	location TEXT,
	acquired_date DATE NOT NULL
);

INSERT INTO assets(name,asset_no,location,acquired_date)
VALUES('Server','10001','Server room','2017-01-01'),
      ('UPS','10002','Server room','2017-01-01');
	  
ALTER TABLE assets
ALTER COLUMN name TYPE VARCHAR;

ALTER TABLE assets
ALTER COLUMN description TYPE VARCHAR,
ALTER COLUMN location TYPE VARCHAR;

ALTER TABLE assets
ALTER COLUMN asset_no TYPE INT;

ALTER TABLE assets
ALTER COLUMN asset_no TYPE INT
USING asset_no::INTEGER;

--RENAME COLUMN: Renaming a column

CREATE TABLE customer_groups(
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL
);

CREATE TABLE customers2(
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	phone VARCHAR NOT NULL,
	email VARCHAR,
	group_id INT,
	FOREIGN KEY (group_id) REFERENCES customer_groups (id)
);

CREATE VIEW customer_date
AS SELECT
	c.id,
	c.name,
	g.name customer_group
FROM customers2 c
INNER JOIN customer_groups g ON g.id = c.group_id;

ALTER TABLE customers2
RENAME COLUMN email TO customer_email;

ALTER TABLE customer_groups
RENAME COLUMN name TO group_name;

ALTER TABLE customers2
RENAME COLUMN name TO customer_name;

ALTER TABLE customers2
RENAME COLUMN phone TO contact_phone;

--DROP TABLE

DROP TABLE authors;
DROP TABLE IF EXISTS author;

CREATE TABLE authors(
	author_id INT PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50)
);

CREATE TABLE pages(
	page_id SERIAL PRIMARY KEY,
	title VARCHAR (255) NOT NULL,
	contents TEXT,
	author_id INT NOT NULL,
	FOREIGN KEY (author_id)
	REFERENCES authors (author_id)
);

DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS authors CASCADE;

CREATE TABLE tvshows(
	tvshow_id INT GENERATED ALWAYS AS IDENTITY,
	title VARCHAR,
	release_year SMALLINT,
	PRIMARY KEY (tvshow_id)
);

CREATE TABLE animes(
	anime_id INT GENERATED ALWAYS AS IDENTITY,
	title VARCHAR,
	release_year SMALLINT,
	PRIMARY KEY (anime_id)
);

DROP TABLE tvshows, animes;



